# [.github/workflows/CI.yml]
name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia-CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-runtest@latest
